# Bridge to CloudMQTT
connection br-me-to-cloudmqtt
bridge_insecure true
address m20.cloudmqtt.com:18088
clientid br-hass
start_type automatic
username zoyuirpg
password e-dykskHgZan
notifications false
try_private true
topic # in

connection awsiot
address a2yiksudz8utkt.iot.eu-central-1.amazonaws.com:8883
topic # out 
bridge_protocol_version mqttv311
bridge_insecure false
cleansession true
clientid bridgeawsiot
start_type automatic
notifications false
log_type all
bridge_cafile /home/nikapov/osmc/awsIotBridge/rootCA.pem
bridge_certfile /home/nikapov/osmc/awsIotBridge/cert.crt
bridge_keyfile /home/nikapov/osmc/awsIotBridge/private.key
