// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:70f3f9e4-718d-4663-b6e1-0c2c653826a8",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_pg3Vcup3R",
    "aws_user_pools_web_client_id": "2phltm8t1oha1dt536f6lijf4c",
    "aws_cloud_logic_custom": [
        {
            "name": "gorico",
            "endpoint": "https://qovyfcdvfj.execute-api.eu-central-1.amazonaws.com/Prod",
            "region": "eu-central-1"
        },
        {
            "name": "goricoprod",
            "endpoint": "https://qybpoq5mdg.execute-api.eu-central-1.amazonaws.com/Prod",
            "region": "eu-central-1"
        }
    ]
};


export default awsmobile;

