// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:074baf0e-b27d-4bd9-b91a-0f3bfecd6de6",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_ESB7XMV6F",
    "aws_user_pools_web_client_id": "7jeiu1l1ch14ai2f7rbr924b9t"
};


export default awsmobile;
